### PR TITLE
PB-726: Added a print progress bar instead of a spinner - #patch

### PR DESCRIPTION
**Pull request by ltshb**
The progress bar is degressive and it's completion time is set based on the
number of layer to print

[Test link](https://sys-map.int.bgdi.ch/preview/feat-print-progress/index.html)

### CODE REVIEW

**Review by hansmannj — APPROVED** [review]
Nice idea! :1st_place_medal: 

Might also make sense, once the printing itself is through and the progess bar is at 100% and disappears, to have a small message there?
When testing on the train with a slow connection to print an A3, the progress bar nicely shows that printing is done.
But downloading an A3 takes quite long and there is no more progress bar of course for that.
But a small message like "downloading PDF" or something might make the user feel more comfortable?

**Comment by ltshb** [comment]
@hansmann for the download time is difficult and behave differently on mobile device and desktop device. On desktop the download is left to the browser and you have the browser download file progress, while on mobile the file is open in a new window.
An issue fix could be to slightly change the success message from "Operation Successful!" to "Print Successful! Downloading..." but then even if the download is done the message will stay so not sure it helps.

**Comment by pakb** [comment]
I don't really like that we do a magic number calculation to decide how to progress the bar, that might backfire in case of future outages, or unforeseen delay (bar being stuck at 99%, like in everyday life on Windows...)

There's no way of giving some steps/progress/feedback from the polling request of the backend?

**Comment by ltshb** [comment]
> I don't really like that we do a magic number calculation to decide how to progress the bar, that might backfire in case of future outages, or unforeseen delay (bar being stuck at 99%, like in everyday life on Windows...)
> 
> There's no way of giving some steps/progress/feedback from the polling request of the backend?

@pakb Unfortunately not that I'm aware off. However your issue is mitigated with https://github.com/geoadmin/infra-kubernetes/pull/568 were the backend timeout after 3min and with my logic here having a degressive progress bar, it will never stays long at 99%, in the worst case for a single layer print it might stay stuck ~1min. We could either decrease the backend timeout to 2min in my opinion ?

**Comment by hansmannj** [comment]
> @hansmann for the download time is difficult and behave differently on mobile device and desktop device. On desktop the download is left to the browser and you have the browser download file progress, while on mobile the file is open in a new window. An issue fix could be to slightly change the success message from "Operation Successful!" to "Print Successful! Downloading..." but then even if the download is done the message will stay so not sure it helps.

Exactly, I don't mean to have  a progress bar for the download, but a message, because the download time is unpredictable

**Comment by hansmannj** [comment]
> > I don't really like that we do a magic number calculation to decide how to progress the bar, that might backfire in case of future outages, or unforeseen delay (bar being stuck at 99%, like in everyday life on Windows...)
> > There's no way of giving some steps/progress/feedback from the polling request of the backend?
> 
> @pakb Unfortunately not that I'm aware off. However your issue is mitigated with [geoadmin/infra-kubernetes#568](https://github.com/geoadmin/infra-kubernetes/pull/568) were the backend timeout after 3min and with my logic here having a degressive progress bar, it will never stays long at 99%, in the worst case for a single layer print it might stay stuck ~1min. We could either decrease the backend timeout to 2min in my opinion ?

Timeout of 2 min might do, just need to test with A3 and a ton of layers. 2 Minutes might be fully used for those cases...

**Review by boecklic — APPROVED** [review]
imho in general a good idea to show to users that print takes time. It's not ideal to set if fixed - arbitrary - value for when it's done, but we don't have a better option right now.

**Comment by ltshb** [comment]
@pakb do you agree to use this ?

**Comment by pakb** [comment]
> @pakb do you agree to use this ?

I don't disagree, I just feel it's a bad solution to a bad problem 😉 (you have a consensus, I think 🤔 )

**Pull request merged**
