### PR TITLE
BGDIINF_SB-3059 : add location popup for 3D

### PR DESCRIPTION
**Pull request by pakb**
Right click on the 3D map now shows the same location popup as in 2D (and it is correctly clamped/anchored to where the click happened)

[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-3059_location_popup_in_3d/index.html)

### CODE REVIEW

**Review by hansmannj — COMMENTED** [review]
In 3D when zooming in or out the tip of the popup moves and does not seem to be anchored to the position of the click

**Comment by ltshb** [comment]
In 2d mode if you use the shortlink generated by the location popup the new view has a cross hair to the position, in 3d you don't have it, is it possible to have crosshair in 3d ?

**Comment by ltshb** [comment]
Same observation as Jürgen, in 3d the location popup is not anchored to the position if moving the map around. Also if you right click at the bottom of the screen the location popup is not fully visible.
Fun fact this PR fixes the location popup in 2d which is currently not working on sys-map.dev.bgdi.ch, it is working on test.map.geo.admin.ch

**Review by ltshb — COMMENTED** [review]
Same observation as Jürgen, in 3d the location popup is not anchored to the position if moving the map around. Also if you right click at the bottom of the screen the location popup is not fully visible.
Fun fact this PR fixes the location popup in 2d which is currently not working on sys-map.dev.bgdi.ch, it is working on test.map.geo.admin.ch

**Review by ltshb — APPROVED** [review]
Code looks good, but I could not test it as I'm currently working on the CI see #522 which temporary breaks it

**Pull request merged**
