### PR TITLE
PB-889: WMS group layer request

### PR DESCRIPTION
**Pull request by ismailsunni**
From the [first example in the ticket](https://map.geo.admin.ch/#/map?lang=en&center=2648907.81,1249803.62&z=3&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&layers=ch.swisstopo.zeitreihen@year=1864,f;ch.bfs.gebaeude_wohnungs_register,f;ch.bav.haltestellen-oev,f;ch.swisstopo.swisstlm3d-wanderwege,f;ch.vbs.schiessanzeigen,f;ch.astra.wanderland-sperrungen_umleitungen,f;WMS%7Chttps://wms.geo.ag.ch/public/ows?SERVICE=WMS%26%7Cch_ag_geo_alg_amphibienzugst&featureInfo=default) this PR reduce from ~30 requests to only 4 requests only. It still have the same behaviour for [the second case](https://map.geo.admin.ch/#/map?lang=en&center=2648907.81,1249803.62&z=3&bgLayer=ch.swisstopo.pixelkarte-farbe&topic=ech&layers=ch.swisstopo.zeitreihen@year=1864,f;ch.bfs.gebaeude_wohnungs_register,f;ch.bav.haltestellen-oev,f;ch.swisstopo.swisstlm3d-wanderwege,f;ch.vbs.schiessanzeigen,f;ch.astra.wanderland-sperrungen_umleitungen,f;WMS%7Chttps://wms.geo.ag.ch/public/ows?SERVICE=WMS%26%7Cch_ag_geo_alg_amphibienzugst&featureInfo=default) 

I can do more so that it only fire one request, but it will change how it looks in the Info Box:
From:
image
To:
image

The difference is the second one will show all selected feature as one layer (because we only fire one request). It might happen also for the current PR.

Looking at the response, we might be able to do the grouping on the frontend with the id. For example: `ch_ag_geo_alg_amphibienzugst_02.54` and `ch_ag_geo_alg_amphibienzugst_01.54`, are from two layer `ch_ag_geo_alg_amphibienzugst_02` and `ch_ag_geo_alg_amphibienzugst_01`, but I am not sure how reliable this pattern.

[Test link](https://sys-map.dev.bgdi.ch/preview/pb-889-wms-group-layer/index.html)

### CODE REVIEW

**Review by pakb — COMMENTED** [review]
There's a little issue with the param BBOX, with this [sample](https://sys-map.dev.bgdi.ch/preview/pb-889-wms-group-layer/index.html#/map?lang=de&center=2684057.89,1245131.47&z=8.391&bgLayer=ch.swisstopo.pixelkarte-grau&topic=ech&layers=WMS%7Chttps://wfs.geodienste.ch/planerischer_gewaesserschutz_v1_1_1/deu?%7Cgewaesserschutzkarte,,0.75) the BBOX sent is something like `BBOX: -3,55,-3,55` but was `BBOX: 2684172,1245205,2684370,1245408` on map.geo.admin.ch

**Comment by ismailsunni** [comment]
@pakb thanks, this is a valid bug actually. When we use different projection, we forget to transform the coordinate. I have fixed it.

**Review by pakb — COMMENTED** [review]
So as discussed on Friday on Slack, there is some debug to be done in regards to the example found in the JIRA ticket

**Comment by ismailsunni** [comment]
@pakb 
Updated with retrieving common CRS from sublayers recursively.
- Example for this PR with layer from the JIRA ticket: https://sys-s.dev.bgdi.ch/n4zu3ml6bc6h
  image

- other example with PR instance: https://sys-s.dev.bgdi.ch/0h7md6p5vwpw
  image

**Review by ltkum — APPROVED** [review]
From what I can tell, this seems to work well.

**Pull request merged**
