### PR TITLE
PB-92: setup fontawsome pro

### PR DESCRIPTION
**Pull request by rebert**
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-pb-92-setup-fontawsome-pro/index.html)

### CODE REVIEW

**Comment by rebert** [comment]
@pakb @ltshb 
With this solution it is possible to work locally without FONTAWESOME_PRO_TOKEN. The pro symbols simply don't show up when running `npm run start`. And there is a message being displayed that `@fortawesome/pro-regular-svg-icons` cannot be loaded.

To setup the CI, we will need to set the FONTAWESOME_PRO_TOKEN and running the command: `npm run build:fontawesome-pro`

**Comment by ltshb** [comment]
On my first try without running `npm run build:fontawesome-pro` I got an error that the import for fontawesome could not be found, then I run the command above and it worked. Unfortunately as I've already run the `build:fontawesome-pro` once I cannot reproduce it ! @pakb could you try as well without the `build:fontawesome-pro` ?

**Comment by pakb** [comment]
image
`npm i` worked fine

I got an error while running `npm run dev`
image

Then it's not possible to open the app in the browser with the given URL, as there's an error
image

So this way of doing it is not sufficiently robust, someone without a FontAwesome pro access can't use our project, and thus contribute

**Comment by ltshb** [comment]
@pakb another issue is that the npm registry for fontawesome (all pro and free) changes when using the pro version and that the new  registry requires authentication even if we only use the free icons. The registry is also saved in the package-lock.json file ! We probably need to refine this during a tecktalk.

**Review by ltshb — COMMENTED** [review]
As discused wait on tecktalk

**Pull request closed without merging**
