### PR TITLE
BGDIINF_SB-226: Inverted add icon for topic tree

### PR DESCRIPTION
**Pull request by fkm**
The add and delete icons look quite similar which can be confusing.

This inverts the colors of the add (plus) icon to make them more distinguishable.

[Test link](https://web-mapviewer.dev.bgdi.ch/feature-jira-bgdiinf_sb-2265-inverted-plus-icon/index.html)

### CODE REVIEW

**Comment by pakb** [comment]
I don't know if we should not stick to rouded icons for this part of the app (so that there is some consistency with layers settings) but use a non filled one for the topic tree. (https://fontawesome.com/icons/circle-plus?s=regular and the same with minus if they are free)

**Comment by davidoesch** [comment]
Rounded  - like in the current viewer

**Comment by fkm** [comment]
Ok. I'll add the borders. That will probably also fix the perceived size. Thank you for the feedback!

**Comment by fkm** [comment]
A propos the FontAwesome Icon with the circle. It looks like only the "solid" version is free.
https://fontawesome.com/search?q=circle&m=free&s=regular

**Review by pakb — APPROVED** [review]

**Pull request merged**
