### PR TITLE
Updated the help link to the new help from the goe.admin.ch CMS

### PR DESCRIPTION
**Pull request by ltshb**
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-help-links/index.html)

### CODE REVIEW

**Review by pakb — APPROVED** [review]

**Comment by ltshb** [comment]
DO not merge YET

**Review by pakb — CHANGES_REQUESTED** [review]
just to make sure we do not merge (ping me when I can approve :wink: )

**Review by ltkum — APPROVED** [review]
After discussing it with @Luke252 : Stefan would prefer that we proceed with this. We can now change the link

**Comment by ltkum** [comment]
> just to make sure we do not merge (ping me when I can approve 😉 )

Whenever you are ready, we can merge this :)

**Pull request merged**
