### PR TITLE
New Release v1.47.0 - #minor

### PR DESCRIPTION
**Pull request by pakb**
[Test link](https://sys-map.int.bgdi.ch/preview/develop/index.html)

### CODE REVIEW

**Comment by pakb** [comment]
we must wait for https://github.com/geoadmin/service-icons/pull/88 to be merged and deploy before going PROD

**Comment by LukasJoss** [comment]
> we must wait for [geoadmin/service-icons#88](https://github.com/geoadmin/service-icons/pull/88) to be merged and deploy before going PROD

Or wait for @hansmannj to check with babs that everything if fine, in that case the image can be deployed without this PR

**Comment by ltshb** [comment]
I tested drawing with babs icon on the tests link (using legacy babs icon and everything works as expecte)

**Comment by ltshb** [comment]
The CI test failure is due to cypress io flaky issue, and as I cannot re-start the CI manually unless we merge a new PR in develop, I'll bypass the branch protection

**Comment by ltshb** [comment]
Drawing with legacy babs icon:
- share link: https://sys-s.int.bgdi.ch/adjmx5kqq3fa
- share link with adminId: https://sys-s.int.bgdi.ch/i92yxiplpehs

**Pull request merged**
