### PR TITLE
Add user's feedback for new viewer

### PR DESCRIPTION
**Pull request by procrastinatio**
For now only with `mailto:`  feedback icon using the `TEST ribbon` not to clutter the viewport.

[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2674_feedback_button/index.html) (added hostname `sys-map.dev.bgdi.ch` to have someting to test. Must be remove before merging)

[Test link](https://sys-map.dev.bgdi.ch/preview/feat_bgdiinf_sb-2674_feedback_button/index.html)

### CODE REVIEW

**Comment by jedef** [comment]
To me it looks good. The only problem that I see is that the word "Test" was removed to give place to the word "Feedback", so now the user does not know anymore that he is on a test site (Or is this visible in another place?). So maybe it would be better if it was somehow possible to fit both on the ribbon.
Also it would be a good idea to add a translation for the subject of the email ("Feedback to new viewer").

**Comment by procrastinatio** [comment]
@jedef, Merci, habe korrigiert.

**Comment by davidoesch** [comment]
I'm still propose to use "report a problem" chnage i to red and renemae it ot " GIVE FEEDBACK"  top right 

- since we then don't expose via mailto our mail adress
- we have a complete feedback of the users environment ( since the feedback modul gives some info back regarding browser and  OS)
-  user does not need to have a mail client installed ( mailto: can be cumbersome on some mobile devices....depending on your settings)


image

**Comment by procrastinatio** [comment]
This PR has been superseeded by https://github.com/geoadmin/web-mapviewer/pull/358

**Pull request closed without merging**
