### PR TITLE
Refactor drawing

### PR DESCRIPTION
**Pull request by pakb**
Contains multiple PRs :

- https://github.com/geoadmin/web-mapviewer/pull/189
- https://github.com/geoadmin/web-mapviewer/pull/194
- https://github.com/geoadmin/web-mapviewer/pull/195
- https://github.com/geoadmin/web-mapviewer/pull/197
- https://github.com/geoadmin/web-mapviewer/pull/198
- https://github.com/geoadmin/web-mapviewer/pull/200
- https://github.com/geoadmin/web-mapviewer/pull/201
- https://github.com/geoadmin/web-mapviewer/pull/202
- https://github.com/geoadmin/web-mapviewer/pull/207
- https://github.com/geoadmin/web-mapviewer/pull/209
- https://github.com/geoadmin/web-mapviewer/pull/213
- https://github.com/geoadmin/web-mapviewer/pull/215
- https://github.com/geoadmin/web-mapviewer/pull/216
- https://github.com/geoadmin/web-mapviewer/pull/217

Plus a couple fixes required after rebasing on `develop` (after the work done on https://github.com/geoadmin/web-mapviewer/pull/206 ) on the last commit

[Test link](https://sys-map.dev.bgdi.ch/develop-refactor-drawing/index.html)

### CODE REVIEW

**Comment by ltshb** [comment]
I guess all the changes have been already reviewed ?
I noticed that the drawing symbol doesn't work, but it doesn't neither on develop branch so for me it is ok to merge this and fix the drawing symbol in a separate PR directly to develop.

**Review by ltshb — COMMENTED** [review]
I'm still not a fan of having all the tests in the `cypress` directory. This is not very intuitive.

**Comment by pakb** [comment]
> I guess all the changes have been already reviewed ? I noticed that the drawing symbol doesn't work, but it doesn't neither on develop branch so for me it is ok to merge this and fix the drawing symbol in a separate PR directly to develop.

That's a CORS issue with `service-icons` somehow...



> I'm still not a fan of having all the tests in the `cypress` directory. This is not very intuitive.

I wouldn't mind putting back a `/e2e-tests/` folder, as unit tests have been moved in the same folder as their tested files

**Comment by pakb** [comment]
> I'm still not a fan of having all the tests in the `cypress` directory. This is not very intuitive.

I've created a ticket for, so that we can go forward with this humongous PR : https://jira.swisstopo.ch/browse/BGDIINF_SB-2419

**Review by ltshb — APPROVED** [review]

**Pull request merged**
