### PR TITLE
BGDIINF_SB-3084 : GUI for import results

### PR DESCRIPTION
**Pull request by vladyslav-tk**
[Test link](https://sys-map.dev.bgdi.ch/preview/feat-bgdiinf_sb-3084-import-result-list/index.html)

### CODE REVIEW

**Comment by vladyslav-tk** [comment]
> 1. When opening the import you have a the place reserved for the result list, might be good to have it responsive and only have the place once you got the results.

then how dropdown should behave? Should we show the list at the top?

Screenshot 2023-10-24 at 13 55 23



> 2. Changing the language doesn't update the result list, would be good to have it updated (aka reloading the external url).

I will have a look

**Comment by vladyslav-tk** [comment]
> 2. Changing the language doesn't update the result list, would be good to have it updated (aka reloading the external url).

done, list reloads on language change

**Comment by ltshb** [comment]
@vladyslav-tk very good point about the dropdown. On the old viewer as the import toolbox is an overlay, the dropdown overflow the box what we cannot do here as it is in the footer. However if you look at this print screen the dropdown is not taking the whole space
image
We could reduce the white space to match the drowpdown list and increase it when the result is displayed, but this could be a bit strange/odd behaviour on the infox box on the footer as it will move the input and connect button higher up. On the old viewer as floating tooltip it looks more natural.
If you can do this behavior easily without spending much time, maybe it is worth a try to see how it behave from a user perspective, otherwise we can leave it as it is now. Thanks

**Review by ltshb — APPROVED** [review]
Very nice, Thanks a lot.

Just one last small issue with the `zoomToExtent`, for the `https://wms.geo.admin.ch` it is then not zoomed to the center of switzerland (comparing to the oldviewer where we can see the whole switzerland in the middle of the view). But as this is probably related to a projection issue and that the whole projection stuff is being reworked in #470 I would not spend time now to try to solve it but I would open a ticket to do it later on, @pakb what do you think.

**Comment by pakb** [comment]
> what do you think.

Let's open a little line of bug/task on our PR so that we do not forget to address this on our projection work

**Comment by ltshb** [comment]
@pakb @vladyslav-tk I created a ticket for the zoom to extent bug that we do it later on, see BGDIINF_SB-3153

**Comment by vladyslav-tk** [comment]
>  We could reduce the white space to match the drowpdown list and increase it when the result is displayed, but this could be a bit strange/odd behaviour on the infox box on the footer as it will move the input and connect button higher up. On the old viewer as floating tooltip it looks more natural. If you can do this behavior easily without spending much time, maybe it is worth a try to see how it behave from a user perspective, otherwise we can leave it as it is now. Thanks

done

**Pull request merged**
