### PR TITLE
Move loading bar at the top

### PR DESCRIPTION
**Pull request by pakb**
Also make it smaller, and with a new loading animation that goes ping pong red/transparent

[Test link](https://web-mapviewer.dev.bgdi.ch/fix_BGDIINF_SB-1416/index.html)

### CODE REVIEW

**Comment by boecklic** [comment]
Is there sth. like a minimum duration (like 0.5s), so that user doesn't have impression of 'flickering' (or even that sth is wrong)?

**Comment by pakb** [comment]
The animation takes a little while to kick in, so we could see there's a grace period of 0.5 sec before you see this happen.
I could also add a little opacity easing to make it less aggressive

**Comment by davidoesch** [comment]
Reference here is google drive. We copied the behavior

Open a google docs/ spreadsheet .
And copy post large amount of data
Loading bar appears 

Also: the mf-Geoadmin3 settings: they are ok and great: not one complaint but several kudos for the feature

so: stick if possible to the existing duration

**Comment by pakb** [comment]
I copied the current animation, I just edited a bit the end of it, so that it would go red the whole screen and then go transparent in the same fashion, not just disappear and start again.
But time wise, it's the same as before

**Review by ltshb — COMMENTED** [review]
I'm not a frontend expert, but would not make sense to put the `HeaderLoadingBar` component on top of the `header` class div in https://github.com/geoadmin/web-mapviewer/blob/8d92bd7f8bb3d1e6c810b64d6b06d659a723a8c5/src/modules/menu/MenuModule.vue#L13 ? This would make the code easier to understand when looking at `MenuModule` component.

**Comment by pakb** [comment]
> I'm not a frontend expert, but would not make sense to put the `HeaderLoadingBar` component on top of the `header` class div 

Totally! It was there because back then it was at the bottom of the menu. But now that it is at the top I should move it accordingly

**Review by ltshb — APPROVED** [review]
:+1:

**Pull request merged**
