### PR TITLE
PB-530: Added print date to the print API spec

### PR DESCRIPTION
**Pull request by ltshb**
Use the date formatting based on the locale (en => MM/DD/YYYY, H:MM PM/AM, fr-CH => DD.MM.YYYY, HH:MM

[Test link](https://sys-map.dev.bgdi.ch/preview/bug-pb-530-print-date/index.html)

### CODE REVIEW

**Review by pakb — COMMENTED** [review]
I'm not sure we shouldn't be sending a proper ISO-8601 datestring instead, while testing and looking at what was sent and then received I see some timezone issue.

I started a job with a date sent that was `"printDate": "5/23/2024, 8:20 AM"` but the file I received in return had `Printed on 23.05.2024 06:20` (so the GMT+2 delta)

Have you tested sending a full ISO string ?

**Comment by ltshb** [comment]
> I'm not sure we shouldn't be sending a proper ISO-8601 datestring instead, while testing and looking at what was sent and then received I see some timezone issue.
> 
> I started a job with a date sent that was `"printDate": "5/23/2024, 8:20 AM"` but the file I received in return had `Printed on 23.05.2024 06:20` (so the GMT+2 delta)
> 
> Have you tested sending a full ISO string ?

Thats because the backend has not been built and deployed yet see https://github.com/geoadmin/service-print3/pull/37

**Review by pakb — APPROVED** [review]
Then all good, maybe we should wait for the PR on the backend side to be merged/deployed, then test the result here, and merge when we are happy with what we see

**Comment by ltshb** [comment]
Tested with the new backend deployment and looks good

**Pull request merged**
